# Site settings
title: stepsame's blog
email: 
description: 试一试静态博客
baseurl: "/try-jekyll"
url: ""

author:
  name     : 'stepsame'
  email    : 
  url      : 
  facebook : 
  twitter  : 

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
